### ISSUE TITLE
Cargo fails to build: error[E0658]: use of unstable library feature 'thread_local_state': state querying was recently added (see issue #27716)

### ISSUE THREAD

**Issue by Lyamc** [maekawatoshiki/naglfar#3]
`$ cargo run
   Compiling parking_lot_core v0.3.0
   Compiling app_units v0.6.1
   Compiling libflate v0.1.16
   Compiling serde_urlencoded v0.5.3
   Compiling mime v0.3.9
   Compiling phf_shared v0.7.23
   Compiling crossbeam-epoch v0.5.2
   Compiling atk-sys v0.6.0
   Compiling gobject-sys v0.6.0
error[E0658]: use of unstable library feature 'thread_local_state': state querying was recently added (see issue #27716)
   --> /home/lyam/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.3.0/src/parking_lot.rs:169:34
    |
169 |     if let Ok(tls) = THREAD_DATA.try_with(|x| x as *const ThreadData) {
    |                                  ^^^^^^^^

error[E0658]: use of unstable library feature 'thread_local_state': state querying was recently added (see issue #27716)
  --> /home/lyam/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.3.0/src/word_lock.rs:55:38
   |
55 |         if let Ok(tls) = THREAD_DATA.try_with(|x| x as *const ThreadData) {
   |                                      ^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `parking_lot_core`.
warning: build failed, waiting for other jobs to finish...
error: build failed
`

**Comment by maekawatoshiki** [comment]
Please try building with nightly Rust.

**Comment by Lyamc** [comment]
I finally got around to testing it again, and yes, it was in fact the nightly rust build.
