### ISSUE TITLE
cargo build error: failed to select a version for the requirement `fragile = "^0.3"`

### ISSUE THREAD

**Issue by wwmmzz** [maekawatoshiki/naglfar#5]
➜  naglfar git:(master) ✗ cargo build
    Updating crates.io index
error: failed to select a version for the requirement `fragile = "^0.3"`
candidate versions found which didn't match: 2.0.0, 1.2.2
location searched: crates.io index
required by package `gio v0.5.0`
    ... which satisfies dependency `gio = "^0.5.0"` of package `gdk v0.9.0`
    ... which satisfies dependency `gdk = "^0.9.0"` of package `gtk v0.5.0`
    ... which satisfies dependency `gtk = "^0.5.0"` of package `naglfar v0.1.6

➜  naglfar git:(master) rustc --version
rustc 1.68.0-nightly (b569c9dc5 2022-12-21)

**Comment by maekawatoshiki** [comment]
~~I'll organize dependencies and add `Cargo.lock`.~~
Added `Cargo.lock` so that you should be able to build it.

**Comment by wwmmzz** [comment]
Thanks for such a quick reply in such a day, solved my problem

this is a amazing project, I learned a lot from this project 
Inotice that you have a js engine project [Rapidus](https://github.com/maekawatoshiki/rapidus)
is there any plan to add js capability for this browser.

best wishes, happy Christmas Eve and Merry Christmas

**Comment by maekawatoshiki** [comment]
I appreciate you got interested in my projects.
At that time I was developing this web browser and the JS engine, I was willing to integrate them.

However, my recent interests are far from that. Actually I'm working on something totally different from web browsers (https://github.com/maekawatoshiki/altius).

I'm glad that you learned something from my projects.
And again, happy holidays.
